const icons = [
  { name: "airplane-outline", id: 1 },
  { name: "albums-outline", id: 2 },
  { name: "bag-outline", id: 3 },
  { name: "bag-handle-outline", id: 4 },
  { name: "bandage-outline", id: 5 },
  { name: "barbell-outline", id: 6 },
  { name: "basket-outline", id: 7 },
  { name: "basketball-outline", id: 8 },
  { name: "bed-outline", id: 9 },
  { name: "beer-outline", id: 10 },
  { name: "bicycle-outline", id: 11 },
  { name: "boat-outline", id: 12 },
  { name: "book-outline", id: 13 },
  { name: "brush-outline", id: 14 },
  { name: "build-outline", id: 15 },
  { name: "bus-outline", id: 16 },
  { name: "cafe-outline", id: 17 },
  { name: "call-outline", id: 18 },
  { name: "car-outline", id: 19 },
  { name: "cart-outline", id: 20 },
  { name: "construct-outline", id: 21 },
  { name: "desktop-outline", id: 22 },
  { name: "diamond-outline", id: 23 },
  { name: "dice-outline", id: 24 },
  { name: "extension-puzzle-outline", id: 25 },
  { name: "fast-food-outline", id: 26 },
  { name: "film-outline", id: 27 },
  { name: "flower-outline", id: 28 },
  { name: "footsteps-outline", id: 29 },
  { name: "game-controller-outline", id: 30 },
  { name: "gift-outline", id: 31 },
  { name: "happy-outline", id: 32 },
  { name: "headset-outline", id: 33 },
  { name: "library-outline", id: 34 },
  { name: "musical-notes-outline", id: 35 },
  { name: "paw-outline", id: 36 },
  { name: "restaurant-outline", id: 37 },
  { name: "subway-outline", id: 38 },
  { name: "ticket-outline", id: 39 },
  { name: "color-palette-outline", id: 40 },
];

export default icons;
